---
title: "Kindergarten Readiness & Developing Self Regulation"
description: |
  Developing "self-regulation" in kids is important for all ages, but especially during the Kindergarten transition. Read about some simple steps for encouraging self-regulation in your preschool classroom.
author:
  - name: Leilani Saez
date: 10-28-2019
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# What is Kindergarten Readiness?
Increasingly, the importance of children beginning Kindergarten “ready to learn” is becoming much clearer, although views on “Kindergarten readiness” can vary widely, and only half of U. S. states have formal definitions to guide practice (IES REL Northwest, 2018). Thirteen years ago, the American Federation of Teachers (AFT) and the National Center for Learning Disabilities (NCLD) created a “Kindergarten Readiness Indicators [Checklist](https://www.aft.org/sites/default/files/t2k_schoolreadiness.pdf)” (2006) that included 40 skills to be evaluated at fall, winter, and spring as an early attempt to provide guidance about the skills children need to develop in preparation for school. It focused on the development of the following main competencies (click the link above to learn more about each indicator):

*	4 indicators of Expressive and Receptive Language
*	9 indicators of Approaches to Learning and Cognition
*	8 indicators of Social and Emotional Development
*	9 indicators of Phonological Awareness and Print Knowledge
*	7 indicators of Mathematics
*	3 indicators of Physical Development

In general, without the establishment of basic competencies prior to Kindergarten, children are at greater risk for poor outcomes in school because they are less capable of adapting to different expectations that they encounter (Egeland, Carlson, & Sroufe, 1993). Learning in an elementary classroom is a different experience than Preschool and home-based environments, and it naturally involves some degree of adjustment as children develop as “student learners”. Although much debate surrounds the specific indicators that matter most (and readiness lists can vary widely in the indicators that they list), the above areas often form a basic view of readiness that considers the whole child beyond just academic knowledge. 

Because the Prekindergarten year precedes school entry, helping children become “Kindergarten ready” may also include the timely cultivation of “life skills” to buffer against home adversities that disadvantage their achievement and health (Fischella & Kitzman, 2009), and facilitate their adjustment. For example, inherently part of preparing most children for Kindergarten involves helping them “learn how to learn” within a classroom setting (Rimm-Kaufman & Pianta, 2000). Children need to be able to follow directions diffused to an entire class, learn specific academic knowledge and procedures with varying levels of assistance, cooperatively share classroom resources, successfully navigate the environment, and effectively self-manage (or regulate) their thoughts, feelings, and behaviors. How well they can behave in accordance with set rules not only influences their social standing with peers, but the quality of relationship with the teacher, feelings about one’s self, and classroom engagement, which can have long-term effects on their emergent school success (Goble, Eggum-Wilkens, Bryce, Foster, Hanish, Martin, & Fabes, 2017). Thus, “life skill” self-regulation that enhances children’s ability to manage school complexity can also enable personal resilience for life (Nota, Soresi, & Zimmerman, 2004). For example, the use of strategies to regulate one’s emotional well-being is associated with better coping of challenges (Tugade & Fredrickson, 2007), something that regularly emerges inside and outside of the classroom. 

# What is Self-regulation? 
Self-regulation involves the emerging capability of children to manage their emotions, attentional focus, physiological (body) responses, behavioral impulses, and cognitive processing for engaging in goal-directed activities (Rimm-Kaufman, Curby, Grimm, Nathanson, & Brock, 2009). Even when children want to behave in a certain way, if they haven’t mastered control of their thoughts and feelings, they are vulnerable to mental overload and feelings of emotional overwhelm that can undermine their best intentions. According to Albert Bandura, our behaviors are based on internal goals (i.e., what we believe is acceptable), which shape how we control our thoughts, feelings, motivations, and behaviors (Bandura, 1991).  In school, there are all kinds of external expectations for behavior that lead children to act in goal-directed ways: completing academic assignments to get good marks, making friends and working cooperatively with peers to gain acceptance, appropriately seeking help to get basic needs met (e.g., with learning, purchasing lunch, using the bathroom in time), and achieving attention from the teacher to feel valued. Therefore, strong self-regulation capabilities enable children to learn and effectively engage with complex (academic, social, emotional, and physical) information, varying conditions, and external expectations that all play a role in their classroom “learning”. 

Although temperament and cognitive processing differences influence the emergence of self-regulation through their effect on children’s reactivity (Rothbart, 2007), many aspects of Preschool learning can also influence it. For example, establishing clear classroom rules and routines; introducing activities; providing warm support; using explicit instruction, modeling, discussion, and practice techniques for skill-building can contribute to gains in self-regulated school readiness because they cultivate planning, problem solving, and intentional learning capacities (Bierman, Nix, Greenberg, Blair, & Domitrovich, 2008).

# How can Self-regulation & Kindergarten Readiness Co-develop?
The Office of Planning, Research, & Evaluation (2019) has a helpful preschool self-regulation [tip sheet](https://www.acf.hhs.gov/opre/research/project/toxic-stress-and-self-regulation-reports) for supporting the development of self-regulation, which I’ll summarize and expand upon below :

### **1.	Incorporate intentional ways to shape healthy social-emotional management for growing self-regulation:**

  **A. Build trusting, warm relationships.** Self-regulation can’t effectively grow under the threat of fear, so focus on developing trust when you interact with the children in your class. Fear leads to quick, reactionary “fight, flight, or freeze” responding instead of deliberate choice-making, which underlies self-regulation. Become a co-regulation partner with children by helping them to manage their feelings (e.g., by “thinking aloud” with them, asking helpful questions, prompting beneficial strategies). Do small things (ask questions, spend time listening, remember information about their lives that is important to them) to learn about and bond with children in your class each day. 

In addition, monitor your own emotional, cognitive, and physiological state to model balanced functioning. For example, notice your level of stress, identify (without judgement) your stress “hot buttons”, and find soothing or proactive ways of dealing with them so you can be at your best in the classroom. The better regulated you are to help children “co-regulate,” the easier and more effectively you will help them learn how to self-manage how they feel, think, and do in your classroom. 

  **B.	Structure the classroom environment to be calm** (yet engaging), **fair and safe** (to foster risk-taking), **predictable** (to enable routines and decrease uncertainty, which empowers independence), and **positive** (to validate children’s worth).  This includes having an evidence-based plan or curriculum for effectively responding to children’s emotional needs that strengthens relationships, clarifies effective ways for children to think about their feelings and appropriate responding, and provides developmentally appropriate practice with “owning” their regulation to remain balanced (i.e., not overstimulated, emotionally out-of-control, or under-stimulated/bored). 

  **C.	Cultivate community where children can contribute to the success of everyone’s well-being.** Give them responsibilities, rules/expectations, and opportunities to shine. Also, help children recover from disappointments, as well as reach out to others to help get their needs met. Part of this work involves building bridges with parents- communicate with them about your efforts to develop self-regulation (and give them ideas for how they can extend it at home), create in-class opportunities that enable them to participate in self-regulation practice, and clearly prioritize self-regulation like other developmental domains (in talking with other staff, others).  


### **2.	Incorporate intentional ways to shape critical thinking as children learn readiness skills by focusing on the processes involved in what they're doing:** 

  **A.	Engage children in thought-provoking activities.** Provide opportunities for children to stretch their imaginations, build perspective-taking, and add to their understanding about concepts. Child-centered play activities naturally cultivate these cognitive skills, but they can even be facilitated when strategically using basic worksheets, by intentionally helping children to “think beyond” the page. For example, when using a coloring sheet, tap into children’s imaginations (rather than have them simply color it) by asking questions, facilitate perspective-taking by prompting sharing of each other’s work, and expand background knowledge by discussing relevant information related to the worksheet (e.g., while coloring a snowman, talk about what snow is and different memories of experiencing snow). 

  **B.	Help children be active noticers.** Although children can be observant, they may not know how to “connect the dots” to notice connections, which is an important skill in self-regulation. For example, knowing why or how something is linked to something else helps children analyze cause and effects.  So, explain changes in *schedule* (e.g., “We need to eat snack early today because we’re taking a field-trip during our regular snack time.”), *setting* (e.g., “Can anyone find the change we made to our Wonder Wall? I took a vacation to Hawaii and found something really interesting to share!”), *feelings* (e.g., “Did you notice that he looks sad? Maybe you can ask him if he doesn’t feel like playing right now because he’s sad.”), and *tasks* (e.g., “It looks like when she put that block on the tower, it made the whole thing fall down. What do you think happened?”). Talking with children in this way helps them learn to focus their attention to what’s happening around them, including how things change (which benefits their understanding about how feelings can change, and how they can instigate changes in how they feel and what they do). Be sure to encourage non-judgmental noticing so that children practice making connections without evaluating whether they are good or bad.

  **C.	Encourage children to become experts in how their minds and bodies work together to accomplish tasks.** Point out where children seem to be putting their attention- is it on *how they feel* (physically or emotionally), *the activity* (maybe the teacher’s directions, a question they have, or something about the task), or *the environment* (a classmate disruption, an adult entering the room, sun shining through the window)- and help them make connections with what’s going on in their mind and body. Watch this 4-minute [video](https://www.mindfulschools.org/resources/explore-mindful-resources/) of children explaining this mindfulness concept.  How can they get help and take some control over what’s going on inside their body? In learning how to respond to what happens in their bodies and the environment, children become more adept at taking action to manage their physiological (e.g., hunger, warmth, comfort) and emotional needs to stay balanced/regulated. 

### Summing Up
The development of self-regulation essentially helps children grow a set of life skills that can positively impact all other developmental domains associated with Kindergarten readiness (language, social-emotional, academic, and physical) because they enable children to self-manage their emotions using their thinking and behavior. Cultivating self-regulation in the classroom can go a long way toward creating a strong foundation in time for school. When children are cognitively or emotionally out of balance (e.g., over- or under-stimulated), they cannot behave or learn at their best. Like the “Goldilocks principle”, too much or too little can prevent learning from being “just right” (we’ll discuss this more in another blog post). 

# Take-Home Message:
Over time, a responsive preschool teacher can help children develop self-regulation by: 

a) Helping children become aware of their current state (mind, body, & heart), and labeling their experience (e.g., instead of “really, really mad”, teach children to state how they feel as “frustrated”, and to make connections with what caused the feeling)

b) Intentionally teaching children how they can help themselves achieve calm (whether frustrated, sad, excited, or afraid)

 c) Supportively practicing and co-regulating the use of strategies that consistently return children to their unique “balance” point (what works for one child may not work for another)
 
Increasing children's awareness about how they're doing, and what they can do to stay in balance for doing their best helps lay the foundation for self-regulation. Like other skills, self-regulated choices can become a habit when communicating needs, learning how to read, joining a peer group, or using scissors. And, with practice, children can become increasingly more competent and confident in how they manage their functioning in school (and life).
